// Generated by CoffeeScript 1.8.0
(function() {
  var timeline;

  timeline = [
    {
      "city": "San Francisco",
      "cover": "embacadero.jpg",
      "title": null,
      "events": [
        {
          "time": "9:10",
          "ampm": "PM",
          "venue": "Home",
          "neighbourhood": "Hayes Valley",
          "note": "Just decided: Netflix is the world's greatest creation."
        }, {
          "time": "7:30",
          "ampm": "PM",
          "venue": "Syrah Wine Bar",
          "neighbourhood": "North Beach",
          "collage": "winebar.jpg",
          "note": "A happy 1 year work anniversary for Sarah and a brilliant collection of wine tastings."
        }, {
          "time": "3:10",
          "ampm": "PM",
          "venue": "The Office",
          "neighbourhood": "Financial District"
        }, {
          "time": "2:50",
          "ampm": "PM",
          "venue": "Dark Roast Cafe",
          "neighbourhood": "Presidio Heights",
          "collage": "darkroast2.jpg",
          "note": "my best friend, the coffee junkie"
        }, {
          "time": "12:30",
          "ampm": "PM",
          "venue": "The Greens Machine",
          "neighbourhood": "South Beach"
        }, {
          "time": "9:20",
          "ampm": "AM",
          "venue": "The Office",
          "neighbourhood": "Financial District"
        }, {
          "time": "9:00",
          "ampm": "AM",
          "venue": "Starbucks",
          "neighbourhood": "Financial District"
        }, {
          "time": "6:40",
          "ampm": "AM",
          "venue": "The Embarcardero",
          "neighbourhood": "Downtown San Francisco",
          "collage": "runningcollage.jpg",
          "note": "Morning runs like this remind me of how lucky I am to live in such a beautiful place."
        }, {
          "time": "6:00",
          "ampm": "AM",
          "venue": "Home",
          "neighbourhood": "Hayes Valley"
        }
      ]
    }, {
      "city": "San Francisco",
      "cover": "../estate.jpg",
      "title": "Flying back home",
      "events": [
        {
          "time": "8:20",
          "ampm": "PM",
          "venue": "Home",
          "neighbourhood": "Hayes Valley"
        }, {
          "time": "7:30",
          "ampm": "PM",
          "venue": "Smitten Icecream",
          "neighbourhood": "Hayes Valley",
          "note": "Tonight's Special: Sweet Basil Icecream. Delicious!"
        }, {
          "time": "5:50",
          "ampm": "PM",
          "venue": "Rich Table",
          "neighbourhood": "Hayes Valley"
        }, {
          "time": "4:10",
          "ampm": "PM",
          "venue": "Home",
          "neighbourhood": "Hayes Valley"
        }, {
          "time": "2:30",
          "ampm": "PM",
          "venue": "San Francisco International Airport",
          "neighbourhood": "San Bruno"
        }, {
          "time": "11:00",
          "ampm": "AM",
          "venue": "Newark International Aiport",
          "neighbourhood": "Newark",
          "note": "I guess it's time to head home"
        }, {
          "time": "9:30",
          "ampm": "AM",
          "venue": "The Estate",
          "neighbourhood": "Old Chatham",
          "collage": "estate.jpg"
        }
      ]
    }, {
      "city": "New York",
      "cover": "estate3.jpg",
      "title": "A day at the estate",
      "events": [
        {
          "time": "7:30",
          "ampm": "PM",
          "venue": "The Estate",
          "neighbourhood": "Old Chatham",
          "collage": "meal.jpg",
          "note": "This amazing dinner with old friends was the highlight of my trip!"
        }, {
          "time": "6:30",
          "ampm": "PM",
          "venue": "New York-New Jersey Line",
          "neighbourhood": "Jersey City",
          "note": "My first time in New Jersey"
        }, {
          "time": "5:10",
          "ampm": "PM",
          "venue": "Jacqueline Kennedy Onassis Reservoir",
          "neighbourhood": "Manhattan",
          "collage": "reserve2.jpg"
        }, {
          "time": "4:30",
          "ampm": "AM",
          "venue": "Big City Bed & Breakfast",
          "neighbourhood": "Upper Manhattan"
        }, {
          "time": "1:30",
          "ampm": "AM",
          "venue": "American Museum of Natural History",
          "neighbourhood": "Upper Manhattan"
        }, {
          "time": "9:50",
          "ampm": "AM",
          "venue": "Manhattan Kitchens",
          "neighbourhood": "Upper Manhattan"
        }, {
          "time": "7:50",
          "ampm": "AM",
          "venue": "Big City Bed & Breakfast",
          "neighbourhood": "Upper Manhattan"
        }
      ]
    }, {
      "city": "New York",
      "title": "",
      "cover": "highline.jpg",
      "events": [
        {
          "time": "10:50",
          "ampm": "PM",
          "venue": "Big City Bed & Breakfast",
          "neighbourhood": "Upper Manhattan"
        }, {
          "time": "8:30",
          "ampm": "PM",
          "venue": "Bareburger",
          "neighbourhood": "West Village"
        }, {
          "time": "5:10",
          "ampm": "PM",
          "venue": "The Highline",
          "neighbourhood": "The Meatpacking District",
          "collage": "highline.jpg",
          "note": "The High Line is a 1-mile linear NYC park, built on a section of the elevated former New York Central Railroad. Such a cool idea"
        }, {
          "time": "4:00",
          "ampm": "PM",
          "venue": "Jefferson Market Courthouse",
          "neighbourhood": "West Village"
        }, {
          "time": "3:20",
          "ampm": "PM",
          "venue": "Magnolia Bakery",
          "neighbourhood": "West Village",
          "collage": "magnolia.jpg",
          "note": "Who says no to a custard filled pumpkin cupcake from Magnolia Bakery?"
        }, {
          "time": "2:30",
          "ampm": "PM",
          "venue": "Subway D- 6 Avenue Express",
          "neighbourhood": "Upper Manhattan"
        }, {
          "time": "1:10",
          "ampm": "PM",
          "venue": "Big City Bed & Breakfast",
          "neighbourhood": "Upper Manhattan",
          "collage": "BandB.jpg"
        }, {
          "time": "1:10",
          "ampm": "PM",
          "venue": "New York Penn Station",
          "neighbourhood": "Midtown West",
          "note": "Hello New York City!"
        }, {
          "time": "11:40",
          "ampm": "AM",
          "venue": "Parson's Truck Stop",
          "neighbourhood": "Greenwich"
        }, {
          "time": "9:00",
          "ampm": "AM",
          "venue": "Boston South Station",
          "neighbourhood": "Boston",
          "note": "until next time, Boston"
        }, {
          "time": "8:50",
          "ampm": "AM",
          "venue": "The Grind",
          "neighbourhood": "Boston"
        }, {
          "time": "8:20",
          "ampm": "AM",
          "venue": "The Charles Hotel",
          "neighbourhood": "Cambridge"
        }
      ]
    }, {
      "city": "Boston",
      "cover": "boston.jpg",
      "title": "Red Sox & Jellyfish",
      "events": [
        {
          "time": "10:20",
          "ampm": "PM",
          "venue": "The Charles Hotel",
          "neighbourhood": "Cambridge"
        }, {
          "time": "8:40",
          "ampm": "PM",
          "venue": "Andrea's Cucina",
          "neighbourhood": "North End",
          "note": "For future reference: order the sweet potato gnocchi!"
        }, {
          "time": "4:30",
          "ampm": "PM",
          "venue": "Fenway Park",
          "collage": "fenway.jpg",
          "neighbourhood": "Boston",
          "note": "Go Red Sox! Singing Sweet Caroline with 30,000 Sox fans was pretty epic."
        }, {
          "time": "2:50",
          "ampm": "PM",
          "venue": "Boston Beer Works",
          "neighbourhood": "Boston"
        }, {
          "time": "10:20",
          "ampm": "AM",
          "venue": "The New England Aquarium",
          "collage": "aquarium.jpg",
          "neighbourhood": "Boston"
        }, {
          "time": "8:40",
          "ampm": "AM",
          "venue": "The Coffee Chateaux",
          "neighbourhood": "Copley Square"
        }, {
          "time": "7:50",
          "ampm": "AM",
          "venue": "The Charles River Promenade",
          "note": "Randomly walked right into a friend from grade school on my walk this morning",
          "neighbourhood": "Cambridge"
        }, {
          "time": "7:30",
          "ampm": "AM",
          "venue": "The Charles Hotel",
          "neighbourhood": "Cambridge"
        }
      ]
    }, {
      "city": "Boston",
      "cover": "garden.jpg",
      "title": null,
      "events": [
        {
          "time": "9:30",
          "ampm": "PM",
          "venue": "The Charles Hotel",
          "neighbourhood": "Cambridge"
        }, {
          "time": "7:40",
          "ampm": "PM",
          "venue": "The Apple & The Fig",
          "neighbourhood": "Beacon Hill"
        }, {
          "time": "6:50",
          "ampm": "PM",
          "venue": "Boston Waterfront",
          "neighbourhood": "Boston",
          "collage": "waterfront.jpg",
          "note": "I could get used to this"
        }, {
          "time": "4:30",
          "ampm": "PM",
          "venue": "Faneuil Hall Marketplace",
          "neighbourhood": "Boston"
        }, {
          "time": "4:10",
          "ampm": "PM",
          "venue": "Boston Public Garden",
          "neighbourhood": "South Boston",
          "note": "I finally met up with Beth at the Gardens. I can't believe how beautiful Boston is- no wonder she likes it here",
          "collage": "bostongarden.jpg"
        }, {
          "time": "3:30",
          "ampm": "PM",
          "venue": "The Charles Hotel",
          "neighbourhood": "Cambridge",
          "collage": "charleshotel.jpg"
        }, {
          "time": "2:50",
          "ampm": "PM",
          "venue": "Boston International Airport",
          "neighbourhood": "East Boston"
        }, {
          "time": "5:30",
          "ampm": "AM",
          "venue": "San Francisco International Airport",
          "neighbourhood": "San Bruno"
        }
      ]
    }
  ];

  $(document).ready(function() {
    var $timeline, ago, compile_day, day, day_template, event_template, get_abs_date, get_date, get_datedelta, get_lockscreen_date, get_week, lock_phone, release_slider, set_time, slideshow_data, start_tutorial, stop_tutorial, unlock_phone, update_position, update_slider, _i, _len;
    this.old_percent = 0;
    this.old_pos = 0;
    this.months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    this.short_months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    this.days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
    this.scroll_headers = {};
    this.current_buffer = 0;
    this.current_slide = 0;
    this.scrolled_to_bottom = false;
    slideshow_data = [
      {
        url: "" + IMG_PATH + "timeline/slideshow/bandb.jpg",
        ago: 3,
        venue: "Big City Bed & Breakfast"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/estate3.jpg",
        ago: 2,
        venue: "The Estate"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/boston.jpg",
        ago: 5,
        venue: "Boston Waterfront"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/darkroast.jpg",
        ago: 0,
        venue: "Dark Roast Cafe"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/estate.jpg",
        ago: 1,
        venue: "The Estate"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/garden.jpg",
        ago: 5,
        venue: "Boston Public Garden"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/highline.jpg",
        ago: 3,
        venue: "The Highline"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/embacadero.jpg",
        ago: 0,
        venue: "The Embacadero"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/estate2.jpg",
        ago: 2,
        venue: "The Estate"
      }, {
        url: "" + IMG_PATH + "timeline/slideshow/fenway.jpg",
        ago: 4,
        venue: "Fenway Park"
      }
    ];
    day_template = "<ul class='day'> <li class='dayheader'> <span class='date'>$date</span> <div class='share'></div> </li> <li class='cover' style='background-image: url(" + IMG_PATH + "timeline/slideshow/$cover);'> <div class='cover_inner'> <p class='date'>$title</p> <p class='city'>$city</p> </div> </li> $events </ul>";
    event_template = '<li> <div class="title"> <div class="time"> <span class="hour">$time</span> <span class="ampm">$ampm</span> </div> <p class="note">$note</p> <p class="venue">$venue <span class="neighbourhood">in $neighbourhood</span></p> </div> $collage </li>';
    compile_day = (function(_this) {
      return function(day, ago) {
        var day_html, event, event_html, event_html_full, _i, _ref;
        event_html_full = "";
        _ref = day.events;
        for (_i = _ref.length - 1; _i >= 0; _i += -1) {
          event = _ref[_i];
          event_html = event_template.replace("$time", event.time).replace("$ampm", event.ampm).replace("$venue", event.venue).replace("$neighbourhood", event.neighbourhood);
          event_html = event_html.replace("$note", event.note ? "<span class='note'>" + event.note + "</span>" : "");
          if (event.collage) {
            event.collage = "" + IMG_PATH + "timeline/" + event.collage;
          }
          event_html = event_html.replace("$collage", event.collage ? "<div class='collage' style='background-image: url(" + event.collage + ")'></div>" : "");
          event_html_full += event_html;
        }
        day_html = day_template.replace("$date", get_date(ago)).replace("$title", day.title || get_datedelta(ago)).replace("$city", day.city).replace("$cover", day.cover).replace("$events", event_html_full);
        return day_html;
      };
    })(this);
    set_time = (function(_this) {
      return function() {
        var d, h, m, pm;
        d = new Date();
        m = d.getMinutes();
        h = d.getHours();
        if (h > 12) {
          pm = "PM";
          h -= 12;
        } else {
          pm = "AM";
        }
        if (m < 10) {
          m = "0" + m;
        }
        $("#statusbar span").text("" + h + ":" + m + " " + pm);
        $(".bigtime").text("" + h + ":" + m);
        return setTimeout(set_time, 60000 - d.getSeconds() * 1000);
      };
    })(this);
    get_week = (function(_this) {
      return function(d) {
        var weekNo, yearStart;
        d = new Date(d);
        d.setHours(0, 0, 0);
        d.setDate(d.getDate() + 4 - (d.getDay() || 7));
        yearStart = new Date(d.getFullYear(), 0, 1);
        weekNo = Math.ceil((((d - yearStart) / 86400000) + 1) / 7);
        return weekNo;
      };
    })(this);
    get_date = (function(_this) {
      return function(ago) {
        var day;
        day = new Date();
        day.setDate(day.getDate() - ago);
        return "" + _this.months[day.getMonth()] + " " + (day.getDate()) + ", " + (day.getFullYear());
      };
    })(this);
    get_abs_date = (function(_this) {
      return function(ago) {
        var day;
        day = new Date();
        day.setDate(day.getDate() - ago);
        return "" + _this.months[day.getMonth()] + " " + (day.getDate()) + ", " + (day.getFullYear());
      };
    })(this);
    get_datedelta = (function(_this) {
      return function(ago) {
        var day, today;
        today = new Date();
        day = new Date();
        day.setDate(day.getDate() - ago);
        if (get_week(today) - get_week(day) % 52 === 0) {
          return _this.days[day.getDay() ? day.getDay() - 1 % 7 : 6];
        }
        if (get_week(today) - get_week(day) % 52 === 1) {
          return "Last " + _this.days[day.getDay() ? day.getDay() - 1 % 7 : 6];
        }
        return "" + _this.short_months[day.getMonth() - 1 % 2] + " " + (day.getDate()) + " " + (day.getFullYear());
      };
    })(this);
    get_lockscreen_date = (function(_this) {
      return function() {
        var today;
        today = new Date();
        return "" + _this.days[today.getDay() ? today.getDay() - 1 % 7 : 6] + ", " + _this.months[today.getMonth()] + " " + (today.getDate());
      };
    })(this);
    update_position = (function(_this) {
      return function() {
        var header_pos, percent, pos, titles, _ref;
        pos = -_this.scroller.y;
        _ref = _this.scroll_headers;
        for (header_pos in _ref) {
          titles = _ref[header_pos];
          if ((_this.old_pos < header_pos && header_pos <= pos)) {
            _this.$date.text(titles[0]);
          } else if ((pos < header_pos && header_pos <= _this.old_pos)) {
            _this.$date.text(titles[1]);
          }
        }
        percent = pos / _this.scroll_stop;
        if (pos >= _this.timeline_height && !_this.scrolled_to_bottom) {
          _this.scrolled_to_bottom = true;
          mixpanel.track("Landing: Scrolled to end of timeline");
        }
        if (pos < 0) {
          $("#slideshow").css({
            'height': _this.slideshow_height - pos + "px",
            "margin-top": pos + "px"
          });
        }
        _this.old_percent = percent;
        return _this.old_pos = pos;
      };
    })(this);
    stop_tutorial = (function(_this) {
      return function() {
        var t, _i, _len, _ref;
        _this.continue_tutorial = false;
        if (_this.timeouts && _this.timeouts.length > 0) {
          mixpanel.track("Landing: Tutorial stopped");
          _ref = _this.timeouts;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            t = _ref[_i];
            clearTimeout(_this.timeouts[t]);
          }
          if (_this.tutorial_timeout) {
            clearTimeout(_this.tutorial_timeout);
          }
          _this.timeouts = [];
          return $("#tooltipslide").addClass('disabled');
        }
      };
    })(this);
    start_tutorial = (function(_this) {
      return function() {
        if (!_this.continue_tutorial) {
          return;
        }
        $("#tooltipslide").removeClass('hidden');
        return _this.timeouts = [
          setTimeout((function() {
            if (_this.continue_tutorial) {
              return $("#tooltipslide").addClass("visible");
            }
          }), 2000), setTimeout((function() {
            if (_this.continue_tutorial) {
              return _this.scroller.scrollTo(0, -424, 2000, IScroll.ease.quadratic);
            }
          }), 3000), setTimeout((function() {
            if (_this.continue_tutorial) {
              return _this.scroller.scrollTo(0, 0, 2000, IScroll.ease.quadratic);
            }
          }), 6000), setTimeout((function() {
            if (!_this.continue_tutorial) {
              return;
            }
            $("#tooltipslide").removeClass("visible").addClass('hidden');
            return _this.tutorial_timeout = setTimeout(start_tutorial, 5000);
          }), 6000)
        ];
      };
    })(this);
    release_slider = (function(_this) {
      return function() {
        var pos;
        pos = _this.slider.x + _this.screen_width;
        if ((0 < pos && pos < 100)) {
          return _this.slider.scrollTo(_this.screen_width, 0, 600);
        } else if (pos >= 100) {
          _this.slider._events['scroll'] = [];
          _this.slider._events['scrollEnd'] = [];
          return unlock_phone();
        }
      };
    })(this);
    update_slider = (function(_this) {
      return function() {
        var pos;
        pos = _this.slider.x + _this.screen_width;
        $("#tooltip").addClass("hiddenagain");
        $("#tooltip").css("-webkit-opacity", .5 - _this.slider.x / 640);
        $("#tophandle").css('margin-top', (-_this.slider.x / 16 - 13) + "px");
        return $(".lockscreen-bg").css("opacity", .5 - _this.slider.x / 640);
      };
    })(this);
    lock_phone = (function(_this) {
      return function() {
        _this.slider = new IScroll("#lockscreen", {
          probeType: 3,
          scrollX: true,
          scrollY: false,
          mouseWheel: true,
          momentum: false,
          bounce: false
        });
        _this.slider.scrollTo(-_this.screen_width, 0, 0);
        _this.slider.on('scrollEnd', release_slider);
        return _this.slider.on('scroll', update_slider);
      };
    })(this);
    unlock_phone = (function(_this) {
      return function() {
        $(".lockscreen-bg").fadeOut(400);
        _this.slider.scrollTo(0, 0, 600);
        $("#tophandle").animate({
          'margin-top': "-10px"
        }, 600);
        return setTimeout((function() {
          $("#iphone").removeClass('locked');
          $("#statusbar span").fadeIn(600);
          $("#iphone-inner-scale").removeClass('scaled');
          setTimeout((function() {
            var total_height;
            total_height = 0;
            return $("ul.day").each(function(ago, e) {
              _this.scroll_headers[total_height + 35] = [get_date(ago), get_date(Math.max(0, ago - 1))];
              return total_height += $(e).height() + 20;
            });
          }), 700);
          _this.scroller = new IScroll("#timeline", {
            probeType: 3,
            mouseWheel: true
          });
          _this.scroller.on('scroll', update_position);
          _this.scroller.on('scrollEnd', update_position);
          _this.tutorial_timeout = setTimeout(start_tutorial, 2000);
          return _this.scroller.on('scrollStart', stop_tutorial);
        }), 400);
      };
    })(this);
    if (!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
      $("#splash").height($(window).height());
      $(window).resize((function(_this) {
        return function() {
          return $("#splash").height($(window).height());
        };
      })(this));
    }
    $('#learnmore').smoothScroll({
      "speed": 800
    });
    $('#playstore').smoothScroll({
      "speed": 800
    });
    setTimeout(((function(_this) {
      return function() {
        return $("#tooltip").removeClass('hidden');
      };
    })(this)), 4000);
    this.$timelineInner = $("#timeline-inner");
    this.$statusbar = $("#statusbar");
    this.$header = $("#header");
    this.$date = $("#date").text(get_date(0));
    this.$buffer0 = $("#buffer0");
    $timeline = $("#timeline");
    this.$buffer1 = $("#buffer1");
    this.$slidepanel0 = $("#slidepanel0");
    this.$slidepanel1 = $("#slidepanel1");
    this.slideshow_height = $("#slideshow").height();
    this.statusbar_height = this.$statusbar.height();
    this.header_height = this.$header.height();
    this.max_opacity = .9;
    this.scroll_stop = this.slideshow_height - this.statusbar_height - this.header_height;
    this.statusbar_change = .4;
    this.continue_tutorial = true;
    set_time();
    $(".bigdate").text(get_lockscreen_date());
    for (ago = _i = 0, _len = timeline.length; _i < _len; ago = ++_i) {
      day = timeline[ago];
      this.$timelineInner.append(compile_day(day, ago));
    }
    this.$timelineInner.append($('<p id="yourlife">How will the story <br />of <strong>your</strong> life look like?</p>'));
    $timeline.bind('mousewheel', stop_tutorial);
    this.timeline_height = $timeline.height();
    this.screen_width = 375;
    this.screen_height = 667;
    lock_phone();
    this.$statusbar.bind('click', (function(_this) {
      return function() {
        return _this.scroller.scrollTo(0, 0, 600);
      };
    })(this));
    mixpanel.track_links('a.appstore', 'Landing page: App store badge');
    mixpanel.track_links('a.appstore_button', 'Landing page: App store button');
    return mixpanel.track("Landing: Phone loaded");
  });

}).call(this);